let productData = {
  menClothingData: [
    {
      id: "1",
      img: "./DataBase/productImages/Men/Shirt1.webp",
      brand: "GenZzz",
      title: "Loose T-shirt for men",
      price: 799,
      category: "T-Shirts",
    },
    {
      id: "2",
      img: "./DataBase/productImages/Men/Shirt2.webp",
      brand: "GenZzz",
      title: "Regular Fit T-shirt for men",
      price: 399,
      category: "T-Shirts",
    },
    {
      id: "3",
      img: "./DataBase/productImages/Men/Shirt3.webp",
      brand: "GenZzz",
      title: "Slim Fit Polo T-shirt for men",
      price: 799,
      category: "T-Shirts",
    },
    {
      id: "4",
      img: "./DataBase/productImages/Men/Shirt4.jfif",
      brand: "GenZzz",
      title: "Loose Printed T-shirt for men",
      price: 799,
      category: "T-Shirts",
    },
    {
      id: "5",
      img: "./DataBase/productImages/Men/Shirt5.webp",
      brand: "GenZzz",
      title: "Loose Printed T-shirt for men",
      price: 1299,
      category: "T-Shirts",
    },
    {
      id: "6",
      img: "./DataBase/productImages/Men/Shirt6.jfif",
      brand: "GenZzz",
      title: "Loose Printed T-shirt for men",
      price: 799,
      category: "T-Shirts",
    },
    {
      id: "7",
      img: "./DataBase/productImages/Men/Shirt7.webp",
      brand: "GenZzz",
      title: "Oversized Fit T-shirt for men",
      price: 799,
      category: "T-Shirts",
    },
    {
      id: "8",
      img: "./DataBase/productImages/Men/Shirt8.jfif",
      brand: "GenZzz",
      title: "Loose Printed T-shirt  for men",
      price: 799,
      category: "T-Shirts",
    },
    {
      id: "9",
      img: "./DataBase/productImages/Men/Shirt9.webp",
      brand: "GenZzz",
      title: "Loose Printed T-shirt for men",
      price: 1499,
      category: "T-Shirts",
    },
    {
      id: "10",
      img: "./DataBase/productImages/Men/Shirt10.webp",
      brand: "GenZzz",
      title: "Loose Fit T-shirt for men",
      price: 699,
      category: "T-Shirts",
    },

    {
      id: "11",
      img: "./DataBase/productImages/Men/Shirt11.jfif",
      brand: "GenZzz",
      title: "Loose Printed T-shirt for men",
      price: 1499,
      category: "T-Shirts",
    },

    {
      id: "12",
      img: "./DataBase/productImages/Men/Shirt12.webp",
      brand: "GenZzz",
      title: "Loose Fit T-shirt for men",
      price: 699,
      category: "T-Shirts",
    },
    {
      id: "13",
      img: "./DataBase/productImages/Men/Jeans1.webp",
      brand: "GenZzz",
      title: "Regular fit Jeans for men",
      price: 1799,
      category: "Jeans",
    },
    {
      id: "14",
      img: "./DataBase/productImages/Men/Jeans2.webp",
      brand: "GenZzz",
      title: "Loose Jeans for men",
      price: 1999,
      category: "Jeans",
    },
    {
      id: "15",
      img: "./DataBase/productImages/Men/Jeans3.webp",
      brand: "GenZzz",
      title: "Regular fit Jeans for men",
      price: 1799,
      category: "Jeans",
    },
    {
      id: "16",
      img: "./DataBase/productImages/Men/Jeans4.webp",
      brand: "GenZzz",
      title: "Loose Jeans for men",
      price: 2299,
      category: "Jeans",
    },
    {
      id: "17",
      img: "./DataBase/productImages/Men/Jeans5.webp",
      brand: "GenZzz",
      title: "Regular fit Jeans for men",
      price: 1799,
      category: "Jeans",
    },
    {
      id: "18",
      img: "./DataBase/productImages/Men/Jeans6.webp",
      brand: "GenZzz",
      title: "Loose Jeans for men",
      price: 2299,
      category: "Jeans",
    },
    {
      id: "19",
      img: "./DataBase/productImages/Men/Jeans7.webp",
      brand: "GenZzz",
      title: "Slim Jeans for men",
      price: 1799,
      category: "Jeans",
    },
    {
      id: "20",
      img: "./DataBase/productImages/Men/Jeans8.webp",
      brand: "GenZzz",
      title: "Loose Denim Jeans for men",
      price: 2699,
      category: "Jeans",
    },
    {
      id: "21",
      img: "./DataBase/productImages/Men/Jeans9.webp",
      brand: "GenZzz",
      title: "Loose Jeans for men",
      price: 2299,
      category: "Jeans",
    },
    {
      id: "22",
      img: "./DataBase/productImages/Men/Jeans10.webp",
      brand: "GenZzz",
      title: "Baggy Jeans for men",
      price: 2699,
      category: "Jeans",
    },

    {
      id: "23",
      img: "./DataBase/productImages/Men/Jeans11.webp",
      brand: "GenZzz",
      title: "Baggy Jeans for men",
      price: 2699,
      category: "Jeans",
    },

    {
      id: "24",
      img: "./DataBase/productImages/Men/Jeans12.webp",
      brand: "GenZzz",
      title: "Baggy Jeans for men",
      price: 2699,
      category: "Jeans",
    },
    {
      id: "25",
      img: "./DataBase/productImages/Men/Cap1.webp",
      brand: "GenZzz",
      title: "Cap For men",
      price: 999,
      category: "Cap",
    },
    {
      id: "26",
      img: "./DataBase/productImages/Men/Cap2.webp",
      brand: "GenZzz",
      title: "Rough Design Cap for men",
      price: 999,
      category: "Cap",
    },
    {
      id: "27",
      img: "./DataBase/productImages/Men/Cap3.jfif",
      brand: "GenZzz",
      title: "Cap for men",
      price: 999,
      category: "Cap",
    },
    {
      id: "28",
      img: "./DataBase/productImages/Men/Cap4.jfif",
      brand: "GenZzz",
      title: "Cotton Cap for men",
      price: 799,
      category: "Cap",
    },
    {
      id: "29",
      img: "./DataBase/productImages/Men/Cap5.jfif",
      brand: "GenZzz",
      title: "Cotton twill Cap for men",
      price: 599,
      category: "Cap",
    },
    {
      id: "30",
      img: "./DataBase/productImages/Men/Cap6.jfif",
      brand: "GenZzz",
      title: "Cotton Cap for men",
      price: 799,
      category: "Cap",
    },
    {
      id: "31",
      img: "./DataBase/productImages/Men/Cap7.jfif",
      brand: "GenZzz",
      title: "Printed Cap for men",
      price: 999,
      category: "Cap",
    },
    {
      id: "32",
      img: "./DataBase/productImages/Men/Cap8.jfif",
      brand: "GenZzz",
      title: "Cotton twill Cap for men",
      price: 599,
      category: "Cap",
    },
    {
      id: "33",
      img: "./DataBase/productImages/Men/Cap9.jfif",
      brand: "GenZzz",
      title: "Cap for men",
      price: 999,
      category: "Cap",
    },
    {
      id: "34",
      img: "./DataBase/productImages/Men/Cap10.webp",
      brand: "GenZzz",
      title: "Cotton twill Cap for men",
      price: 499,
      category: "Cap",
    },
    {
      id: "35",
      img: "./DataBase/productImages/Men/Cap11.webp",
      brand: "GenZzz",
      title: "Printed Disney Cap for men",
      price: 599,
      category: "Cap",
    },
    {
      id: "36",
      img: "./DataBase/productImages/Men/Cap12.jfif",
      brand: "GenZzz",
      title: "Cotton white Cap for men",
      price: 499,
      category: "Cap",
    },
    {
      id: "37",
      img: "./DataBase/productImages/Men/Shoes1.webp",
      brand: "GenZzz",
      title: "Derby shoes for men",
      price: 2999,
      category: "Shoes",
    },
    {
      id: "38",
      img: "./DataBase/productImages/Men/Shoes2.webp",
      brand: "GenZzz",
      title: "Derby shoes for men",
      price: 2999,
      category: "Shoes",
    },
    {
      id: "39",
      img: "./DataBase/productImages/Men/Shoes3.avif",
      brand: "GenZzz",
      title: "White leather sneakers for men",
      price: 2499,
      category: "Shoes",
    },
    {
      id: "40",
      img: "./DataBase/productImages/Men/Shoes4.avif",
      brand: "GenZzz",
      title: "Shoes for men",
      price: 1999,
      category: "Shoes",
    },
    {
      id: "41",
      img: "./DataBase/productImages/Men/Shoes5.avif",
      brand: "GenZzz",
      title: "White leather sneakers for men",
      price: 1999,
      category: "Shoes",
    },
    {
      id: "42",
      img: "./DataBase/productImages/Men/Shoes6.avif",
      brand: "GenZzz",
      title: "White Sneakers for men",
      price: 1770,
      category: "Shoes",
    },
    {
      id: "43",
      img: "./DataBase/productImages/Men/Shoes7.jpg",
      brand: "GenZzz",
      title: "White sneakers for men",
      price: 3999,
      category: "Shoes",
    },
    {
      id: "44",
      img: "./DataBase/productImages/Men/Shoes8.jpg",
      brand: "GenZzz",
      title: "White sneakers for men",
      price: 1999,
      category: "Shoes",
    },
    {
      id: "45",
      img: "./DataBase/productImages/Men/Shoes9.jpg",
      brand: "GenZzz",
      title: "Black sneakers for men",
      price: 2499,
      category: "Shoes",
    },
    {
      id: "46",
      img: "./DataBase/productImages/Men/Shoes10.jfif",
      brand: "GenZzz",
      title: "Runners for men",
      price: 1999,
      category: "Shoes",
    },
    {
      id: "47",
      img: "./DataBase/productImages/Men/Shoes11.avif",
      brand: "GenZzz",
      title: "Brown sneakers for men",
      price: 1999,
      category: "Shoes",
    },
    {
      id: "48",
      img: "./DataBase/productImages/Men/Shoes12.avif",
      brand: "GenZzz",
      title: "Sneakers for men",
      price: 2499,
      category: "Shoes",
    },
  ],

  kidsClothingData: [
    {
      id: "49",
      img: "./DataBase/productImages/Kid/Shirt1.jfif",
      brand: "GenZzz",
      title: "3-pack T-shirts For Kid",
      price: 519,
      category: "T-Shirts",
    },

    {
      id: "50",
      img: "./DataBase/productImages/Kid/Shirt2.jfif",
      brand: "GenZzz",
      title: "3-pack T-shirts For Kid",
      price: 849,
      category: "T-Shirts",
    },

    {
      id: "51",
      img: "./DataBase/productImages/Kid/Shirt3.jfif",
      brand: "GenZzz",
      title: "2-piece Terry Set For Kid",
      price: 599,
      category: "T-Shirts",
    },

    {
      id: "52",
      img: "./DataBase/productImages/Kid/Shirt4.jfif",
      brand: "GenZzz",
      title: "Long-sleeved T-shirt For Kid",
      price: 399,
      category: "T-Shirts",
    },

    {
      id: "53",
      img: "./DataBase/productImages/Kid/Shirt5.jfif",
      brand: "GenZzz",
      title: "Oversized Printed T-shirt For Kid",
      price: 799,
      category: "T-Shirts",
    },

    {
      id: "54",
      img: "./DataBase/productImages/Kid/Shirt6.jfif",
      brand: "GenZzz",
      title: "2-piece Cotton Set For Kid",
      price: 649,
      category: "T-Shirts",
    },

    {
      id: "55",
      img: "./DataBase/productImages/Kid/Shirt7.jfif",
      brand: "GenZzz",
      title: "Printed T-shirt For Kid",
      price: 359,
      category: "T-Shirts",
    },

    {
      id: "56",
      img: "./DataBase/productImages/Kid/Shirt8.jfif",
      brand: "GenZzz",
      title: "Printed T-shirt For Kid",
      price: 299,
      category: "T-Shirts",
    },

    {
      id: "57",
      img: "./DataBase/productImages/Kid/Shirt9.jfif",
      brand: "GenZzz",
      title: "Printed T-shirt For Kid",
      price: 299,
      category: "T-Shirts",
    },

    {
      id: "58",
      img: "./DataBase/productImages/Kid/Shirt10.jfif",
      brand: "GenZzz",
      title: "Printed T-shirt For Kid",
      price: 299,
      category: "T-Shirts",
    },

    {
      id: "59",
      img: "./DataBase/productImages/Kid/Shirt11.jfif",
      brand: "GenZzz",
      title: "Cotton Jersey T-shirt For Kid",
      price: 399,
      category: "T-Shirts",
    },

    {
      id: "60",
      img: "./DataBase/productImages/Kid/Shirt12.jfif",
      brand: "GenZzz",
      title: "Motif-detail cotton T-shirt For Kid",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "61",
      img: "./DataBase/productImages/Kid/Jeans1.jfif",
      brand: "GenZzz",
      title: "Denim dungarees For Kid",
      price: 1499,
      category: "Jeans",
    },

    {
      id: "62",
      img: "./DataBase/productImages/Kid/Jeans2.jfif",
      brand: "GenZzz",
      title: "Skinny Fit Jeans For Kid",
      price: 799,
      category: "Jeans",
    },

    {
      id: "63",
      img: "./DataBase/productImages/Kid/Jeans3.webp",
      brand: "GenZzz",
      title: "Loose Fit Jeans For Kid",
      price: 1799,
      category: "Jeans",
    },

    {
      id: "64",
      img: "./DataBase/productImages/Kid/Jeans4.webp",
      brand: "GenZzz",
      title: "Jeggings For Kid",
      price: 899,
      category: "Jeans",
    },

    {
      id: "65",
      img: "./DataBase/productImages/Kid/Jeans5.webp",
      brand: "GenZzz",
      title: "Slim Fit Jeans For Kid",
      price: 999,
      category: "Jeans",
    },

    {
      id: "66",
      img: "./DataBase/productImages/Kid/Jeans6.jfif",
      brand: "GenZzz",
      title: "Skinny Fit Jeans For Kid",
      price: 799,
      category: "Jeans",
    },

    {
      id: "67",
      img: "./DataBase/productImages/Kid/Jeans7.jfif",
      brand: "GenZzz",
      title: "Superstretch Jeans For Kid",
      price: 799,
      category: "Jeans",
    },

    {
      id: "68",
      img: "./DataBase/productImages/Kid/Jeans8.jfif",
      brand: "GenZzz",
      title: "Relaxed Fit Jeans For Kid",
      price: 1499,
      category: "Jeans",
    },

    {
      id: "69",
      img: "./DataBase/productImages/Kid/Jeans9.jfif",
      brand: "GenZzz",
      title: "Jeggings For Kid",
      price: 1279,
      category: "Jeans",
    },

    {
      id: "70",
      img: "./DataBase/productImages/Kid/Jeans10.jfif",
      brand: "GenZzz",
      title: "Skinny Fit Jeans For Kid",
      price: 799,
      category: "Jeans",
    },

    {
      id: "71",
      img: "./DataBase/productImages/Kid/Jeans11.webp",
      brand: "GenZzz",
      title: "Relaxed Fit Jeans For Kid",
      price: 1799,
      category: "Jeans",
    },

    {
      id: "72",
      img: "./DataBase/productImages/Kid/Jeans12.webp",
      brand: "GenZzz",
      title: "Denim dungarees For Kid",
      price: 1999,
      category: "Jeans",
    },

    {
      id: "73",
      img: "./DataBase/productImages/Kid/Cap1.jfif",
      brand: "GenZzz",
      title: "Motif-detail Cap For Kid",
      price: 799,
      category: "Cap",
    },

    {
      id: "74",
      img: "./DataBase/productImages/Kid/Cap2.jfif",
      brand: "GenZzz",
      title: "Cotton Cap For Kid",
      price: 399,
      category: "Cap",
    },

    {
      id: "75",
      img: "./DataBase/productImages/Kid/Cap3.jfif",
      brand: "GenZzz",
      title: "Cotton Cap For Kid",
      price: 749,
      category: "Cap",
    },

    {
      id: "76",
      img: "./DataBase/productImages/Kid/Cap4.jfif",
      brand: "GenZzz",
      title: "Twill Cap For Kid",
      price: 399,
      category: "Cap",
    },

    {
      id: "77",
      img: "./DataBase/productImages/Kid/Cap5.jfif",
      brand: "GenZzz",
      title: "Motif-detail Cap For Kid",
      price: 749,
      category: "Cap",
    },

    {
      id: "78",
      img: "./DataBase/productImages/Kid/Cap6.jfif",
      brand: "GenZzz",
      title: "Cotton Twill Cap For Kid",
      price: 699,
      category: "Cap",
    },

    {
      id: "79",
      img: "./DataBase/productImages/Kid/Cap7.jfif",
      brand: "GenZzz",
      title: "Cotton Cap For Kid",
      price: 699,
      category: "Cap",
    },

    {
      id: "80",
      img: "./DataBase/productImages/Kid/Cap8.jfif",
      brand: "GenZzz",
      title: "Twill Cap For Kid",
      price: 699,
      category: "Cap",
    },

    {
      id: "81",
      img: "./DataBase/productImages/Kid/Cap9.jfif",
      brand: "GenZzz",
      title: "Cotton Twill Cap For Kid",
      price: 699,
      category: "Cap",
    },

    {
      id: "82",
      img: "./DataBase/productImages/Kid/Cap10.jfif",
      brand: "GenZzz",
      title: "Cotton Cap For Kid",
      price: 699,
      category: "Cap",
    },

    {
      id: "83",
      img: "./DataBase/productImages/Kid/Cap11.jfif",
      brand: "GenZzz",
      title: "Cotton Cap For Kid",
      price: 749,
      category: "Cap",
    },

    {
      id: "84",
      img: "./DataBase/productImages/Kid/Cap12.jfif",
      brand: "GenZzz",
      title: "Flower Printed Cap For Kid",
      price: 799,
      category: "Cap",
    },

    {
      id: "85",
      img: "./DataBase/productImages/Kid/Shoes1.jfif",
      brand: "GenZzz",
      title: "Ballerina Trainers For Kid",
      price: 979,
      category: "Shoes",
    },

    {
      id: "86",
      img: "./DataBase/productImages/Kid/Shoes2.jfif",
      brand: "GenZzz",
      title: "Ballerina Trainers For Kid",
      price: 979,
      category: "Shoes",
    },

    {
      id: "87",
      img: "./DataBase/productImages/Kid/Shoes3.jfif",
      brand: "GenZzz",
      title: "Print-motif Pool Shoes For Kid",
      price: 799,
      category: "Shoes",
    },

    {
      id: "88",
      img: "./DataBase/productImages/Kid/Shoes4.jfif",
      brand: "GenZzz",
      title: "Trainers For Kid",
      price: 899,
      category: "Shoes",
    },

    {
      id: "89",
      img: "./DataBase/productImages/Kid/Shoes5.jfif",
      brand: "GenZzz",
      title: "Strappy Sandals For Kid",
      price: 979,
      category: "Shoes",
    },

    {
      id: "90",
      img: "./DataBase/productImages/Kid/Shoes6.jfif",
      brand: "GenZzz",
      title: "Pool Shoes For Kid",
      price: 829,
      category: "Shoes",
    },

    {
      id: "91",
      img: "./DataBase/productImages/Kid/Shoes7.jfif",
      brand: "GenZzz",
      title: "Printed Pool Shoes For Kid",
      price: 719,
      category: "Shoes",
    },

    {
      id: "92",
      img: "./DataBase/productImages/Kid/Shoes8.jfif",
      brand: "GenZzz",
      title: "Chelsea Boots For Kid",
      price: 2299,
      category: "Shoes",
    },

    {
      id: "93",
      img: "./DataBase/productImages/Kid/Shoes9.jfif",
      brand: "GenZzz",
      title: "Printed Pool Shoes For Kid",
      price: 1169,
      category: "Shoes",
    },

    {
      id: "94",
      img: "./DataBase/productImages/Kid/Shoes10.jfif",
      brand: "GenZzz",
      title: "Printed Pool Slides For Kid",
      price: 1109,
      category: "Shoes",
    },

    {
      id: "95",
      img: "./DataBase/productImages/Kid/Shoes11.jfif",
      brand: "GenZzz",
      title: "Beaded Satin Slides For Kid",
      price: 1599,
      category: "Shoes",
    },

    {
      id: "96",
      img: "./DataBase/productImages/Kid/Shoes12.webp",
      brand: "GenZzz",
      title: "Beaded Slides For Kid",
      price: 1599,
      category: "Shoes",
    },
  ],

  womenClothingData: [
    {
      id: "97",
      img: "./DataBase/productImages/Women/Shirt1.webp",
      brand: "GenZzz",
      title: "Oversized printed T-shirt For Women",
      price: 779,
      category: "T-Shirts",
    },

    {
      id: "98",
      img: "./DataBase/productImages/Women/Shirt2.webp",
      brand: "GenZzz",
      title: "Print-motif T-shirt For Women",
      price: 699,
      category: "T-Shirts",
    },

    {
      id: "99",
      img: "./DataBase/productImages/Women/Shirt3.webp",
      brand: "GenZzz",
      title: "Cotton T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "100",
      img: "./DataBase/productImages/Women/Shirt4.webp",
      brand: "GenZzz",
      title: "Print-motif T-shirt For Women",
      price: 699,
      category: "T-Shirts",
    },

    {
      id: "101",
      img: "./DataBase/productImages/Women/Shirt5.webp",
      brand: "GenZzz",
      title: "Ribbed T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "102",
      img: "./DataBase/productImages/Women/Shirt6.webp",
      brand: "GenZzz",
      title: "Sweetheart-neck T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "103",
      img: "./DataBase/productImages/Women/Shirt7.webp",
      brand: "GenZzz",
      title: "Cotton T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "104",
      img: "./DataBase/productImages/Women/Shirt8.webp",
      brand: "GenZzz",
      title: "Printed T-shirt For Women",
      price: 419,
      category: "T-Shirts",
    },

    {
      id: "105",
      img: "./DataBase/productImages/Women/Shirt9.webp",
      brand: "GenZzz",
      title: "Ribbed T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "106",
      img: "./DataBase/productImages/Women/Shirt10.webp",
      brand: "GenZzz",
      title: "Cropped Cotton T-shirt For Women",
      price: 399,
      category: "T-Shirts",
    },

    {
      id: "107",
      img: "./DataBase/productImages/Women/Shirt11.webp",
      brand: "GenZzz",
      title: "Cotton T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "108",
      img: "./DataBase/productImages/Women/Shirt12.webp",
      brand: "GenZzz",
      title: "Cotton T-shirt For Women",
      price: 499,
      category: "T-Shirts",
    },

    {
      id: "109",
      img: "./DataBase/productImages/Women/Jeans1.webp",
      brand: "GenZzz",
      title: "Wide Fit Jeans For Women",
      price: 1999,
      category: "Jeans",
    },

    {
      id: "110",
      img: "./DataBase/productImages/Women/Jeans2.webp",
      brand: "GenZzz",
      title: "Cargo Trousers/Jeans For Women",
      price: 919,
      category: "Jeans",
    },

    {
      id: "111",
      img: "./DataBase/productImages/Women/Jeans3.webp",
      brand: "GenZzz",
      title: "Flared Low Jeans For Women",
      price: 799,
      category: "Jeans",
    },

    {
      id: "112",
      img: "./DataBase/productImages/Women/Jeans4.webp",
      brand: "GenZzz",
      title: "Slim High Ankle Jeans For Women",
      price: 1399,
      category: "Jeans",
    },

    {
      id: "113",
      img: "./DataBase/productImages/Women/Jeans5.webp",
      brand: "GenZzz",
      title: "Loose Fit Jeans For Women",
      price: 1259,
      category: "Jeans",
    },

    {
      id: "114",
      img: "./DataBase/productImages/Women/Jeans6.webp",
      brand: "GenZzz",
      title: "Skinny Fit Jeans For Women",
      price: 599,
      category: "Jeans",
    },

    {
      id: "115",
      img: "./DataBase/productImages/Women/Jeans7.jfif",
      brand: "GenZzz",
      title: "Straight Fit Jeans For Women",
      price: 1599,
      category: "Jeans",
    },

    {
      id: "116",
      img: "./DataBase/productImages/Women/Jeans8.jfif",
      brand: "GenZzz",
      title: "Flared High Jeans For Women",
      price: 1499,
      category: "Jeans",
    },

    {
      id: "117",
      img: "./DataBase/productImages/Women/Jeans9.webp",
      brand: "GenZzz",
      title: "Baggy Regular Jeans For Women",
      price: 1999,
      category: "Jeans",
    },

    {
      id: "118",
      img: "./DataBase/productImages/Women/Jeans10.webp",
      brand: "GenZzz",
      title: "Straight High Jeans For Women",
      price: 1899,
      category: "Jeans",
    },

    {
      id: "119",
      img: "./DataBase/productImages/Women/Jeans11.webp",
      brand: "GenZzz",
      title: "Skinny Regular Jeans For Women",
      price: 899,
      category: "Jeans",
    },

    {
      id: "120",
      img: "./DataBase/productImages/Women/Jeans12.jfif",
      brand: "GenZzz",
      title: "Baggy Regular Jeans For Women",
      price: 1999,
      category: "Jeans",
    },

    {
      id: "121",
      img: "./DataBase/productImages/Women/Cap1.jfif",
      brand: "GenZzz",
      title: "Cotton Twill Cap for Women",
      price: 699,
      category: "Cap",
    },

    {
      id: "122",
      img: "./DataBase/productImages/Women/Cap2.jfif",
      brand: "GenZzz",
      title: "Washed-Look Denim Cap for Women",
      price: 799,
      category: "Cap",
    },

    {
      id: "123",
      img: "./DataBase/productImages/Women/Cap3.webp",
      brand: "GenZzz",
      title: "Cotton Twill Cap for Women",
      price: 699,
      category: "Cap",
    },

    {
      id: "124",
      img: "./DataBase/productImages/Women/Cap4.jfif",
      brand: "GenZzz",
      title: "Cotton Denim Cap for Women",
      price: 639,
      category: "Cap",
    },

    {
      id: "125",
      img: "./DataBase/productImages/Women/Cap5.jfif",
      brand: "GenZzz",
      title: "Cotton Denim Cap for Women",
      price: 799,
      category: "Cap",
    },

    {
      id: "126",
      img: "./DataBase/productImages/Women/Cap6.jfif",
      brand: "GenZzz",
      title: "Ramie-Blend Cap for Women",
      price: 649,
      category: "Cap",
    },

    {
      id: "127",
      img: "./DataBase/productImages/Women/Cap7.jfif",
      brand: "GenZzz",
      title: "Cotton Cap for Women",
      price: 499,
      category: "Cap",
    },

    {
      id: "128",
      img: "./DataBase/productImages/Women/Cap8.webp",
      brand: "GenZzz",
      title: "Cotton Cap for Women",
      price: 569,
      category: "Cap",
    },

    {
      id: "129",
      img: "./DataBase/productImages/Women/Cap9.jfif",
      brand: "GenZzz",
      title: "Cotton Cap for Women",
      price: 649,
      category: "Cap",
    },

    {
      id: "130",
      img: "./DataBase/productImages/Women/Cap10.webp",
      brand: "GenZzz",
      title: "Cotton twill Cap for Women",
      price: 699,
      category: "Cap",
    },

    {
      id: "131",
      img: "./DataBase/productImages/Women/Cap11.jfif",
      brand: "GenZzz",
      title: "Printed Cap for Women",
      price: 1199,
      category: "Cap",
    },

    {
      id: "132",
      img: "./DataBase/productImages/Women/Cap12.jfif",
      brand: "GenZzz",
      title: "Twill Cap for Women",
      price: 999,
      category: "Cap",
    },

    {
      id: "133",
      img: "./DataBase/productImages/Women/Shoes1.jfif",
      brand: "GenZzz",
      title: "Pointed slingbacks Hill/Shoes For Women",
      price: 1499,
      category: "Shoes",
    },

    {
      id: "134",
      img: "./DataBase/productImages/Women/Shoes2.webp",
      brand: "GenZzz",
      title: "Ballet pumps Shoes For Women",
      price: 1499,
      category: "Shoes",
    },

    {
      id: "135",
      img: "./DataBase/productImages/Women/Shoes3.webp",
      brand: "GenZzz",
      title: "Intertwined-strap Sandals For Women",
      price: 1999,
      category: "Shoes",
    },

    {
      id: "136",
      img: "./DataBase/productImages/Women/Shoes4.webp",
      brand: "GenZzz",
      title: "Block-heeled Sandals For Women",
      price: 1799,
      category: "Shoes",
    },

    {
      id: "137",
      img: "./DataBase/productImages/Women/Shoes5.webp",
      brand: "GenZzz",
      title: "Rhinestone-embellished Mules For Women",
      price: 1439,
      category: "Shoes",
    },

    {
      id: "138",
      img: "./DataBase/productImages/Women/Shoes6.webp",
      brand: "GenZzz",
      title: "Wedge-heeled Espadrille Sandals For Women",
      price: 2999,
      category: "Shoes",
    },

    {
      id: "139",
      img: "./DataBase/productImages/Women/Shoes7.webp",
      brand: "GenZzz",
      title: "Leather Ballet Pump For Womens",
      price: 2999,
      category: "Shoes",
    },

    {
      id: "140",
      img: "./DataBase/productImages/Women/Shoes8.jfif",
      brand: "GenZzz",
      title: "Rhinestone-embellished Mules For Women",
      price: 1539,
      category: "Shoes",
    },

    {
      id: "141",
      img: "./DataBase/productImages/Women/Shoes9.webp",
      brand: "GenZzz",
      title: "Leather Slingbacks For Women",
      price: 2999,
      category: "Shoes",
    },

    {
      id: "142",
      img: "./DataBase/productImages/Women/Shoes10.jfif",
      brand: "GenZzz",
      title: "Chunky Canvas Boots For Women",
      price: 2029,
      category: "Shoes",
    },

    {
      id: "143",
      img: "./DataBase/productImages/Women/Shoes11.webp",
      brand: "GenZzz",
      title: "Rhinestone-embellished boots ",
      price: 5499,
      category: "Shoes",
    },

    {
      id: "144",
      img: "./DataBase/productImages/Women/Shoes12.webp",
      brand: "GenZzz",
      title: "Boots For Women",
      price: 2599,
      category: "Shoes",
    },
  ],

  accessories: [
    {
      id: "145",
      img: "./DataBase/productImages/Accessories/all1.webp",
      brand: "GenZzz",
      title: "2-pack bracelets",
      price: "399",
      category: "all",
    },
    {
      id: "146",
      img: "./DataBase/productImages/Accessories/all2.webp",
      brand: "GenZzz",
      title: "Chunky dome earrings",
      price: "299",
      category: "all",
    },
    {
      id: "147",
      img: "./DataBase/productImages/Accessories/all3.jfif",
      brand: "GenZzz",
      title: "Waist bag",
      price: "899",
      category: "all",
    },
    {
      id: "148",
      img: "./DataBase/productImages/Accessories/all4.webp",
      brand: "GenZzz",
      title: "Shopper",
      price: "1299",
      category: "all",
    },
    {
      id: "149",
      img: "./DataBase/productImages/Accessories/all5.jfif",
      brand: "GenZzz",
      title: "2-pack ribbed ear-detail beanies",
      price: "799",
      category: "all",
    },
    {
      id: "150",
      img: "./DataBase/productImages/Accessories/all6.jfif",
      brand: "GenZzz",
      title: "Bow-decorated scrunchie",
      price: "299",
      category: "all",
    },
    {
      id: "151",
      img: "./DataBase/productImages/Accessories/all7.jfif",
      brand: "GenZzz",
      title: "Belt",
      price: "649",
      category: "all",
    },
    {
      id: "152",
      img: "./DataBase/productImages/Accessories/all8.jfif",
      brand: "GenZzz",
      title: "11-pack rings",
      price: "599",
      category: "all",
    },
    {
      id: "153",
      img: "./DataBase/productImages/Accessories/all9.jfif",
      brand: "GenZzz",
      title: "3-pack rings",
      price: "519",
      category: "all",
    },
    {
      id: "154",
      img: "./DataBase/productImages/Accessories/all10.jfif",
      brand: "GenZzz",
      title: "2-pack necklaces",
      price: "559",
      category: "all",
    },
    {
      id: "155",
      img: "./DataBase/productImages/Accessories/all11.jfif",
      brand: "GenZzz",
      title: "Patterned scarf",
      price: "699",
      category: "all",
    },
    {
      id: "156",
      img: "./DataBase/productImages/Accessories/all12.jfif",
      brand: "GenZzz",
      title: "Jacquard-weave shopper",
      price: "2699",
      category: "all",
    },
    {
      id: "157",
      img: "./DataBase/productImages/Accessories/men1.jfif",
      brand: "GenZzz",
      title: "5-pack rings",
      price: "319",
      category: "men",
    },
    {
      id: "158",
      img: "./DataBase/productImages/Accessories/men2.jfif",
      brand: "GenZzz",
      title: "2-pack bracelets",
      price: "399",
      category: "men",
    },
    {
      id: "159",
      img: "./DataBase/productImages/Accessories/men3.jfif",
      brand: "GenZzz",
      title: "Backpack",
      price: "1429",
      category: "men",
    },
    {
      id: "160",
      img: "./DataBase/productImages/Accessories/men4.jfif",
      brand: "GenZzz",
      title: "Necklace and bracelet",
      price: "399",
      category: "men",
    },
    {
      id: "161",
      img: "./DataBase/productImages/Accessories/men5.jfif",
      brand: "GenZzz",
      title: "2-pack necklaces",
      price: "479",
      category: "men",
    },
    {
      id: "162",
      img: "./DataBase/productImages/Accessories/men6.jfif",
      brand: "GenZzz",
      title: "2-pack rings",
      price: "519",
      category: "men",
    },
    {
      id: "163",
      img: "./DataBase/productImages/Accessories/men7.jfif",
      brand: "GenZzz",
      title: "Flat shoulder bag",
      price: "1149",
      category: "men",
    },
    {
      id: "164",
      img: "./DataBase/productImages/Accessories/men8.webp",
      brand: "GenZzz",
      title: "3-pack necklaces",
      price: "519",
      category: "men",
    },
    {
      id: "165",
      img: "./DataBase/productImages/Accessories/men9.jfif",
      brand: "GenZzz",
      title: "Braided belt",
      price: "699",
      category: "men",
    },
    {
      id: "166",
      img: "./DataBase/productImages/Accessories/men10.jfif",
      brand: "GenZzz",
      title: "Sunglasses",
      price: "559",
      category: "men",
    },
    {
      id: "167",
      img: "./DataBase/productImages/Accessories/men11.jfif",
      brand: "GenZzz",
      title: "Sunglasses",
      price: "479",
      category: "men",
    },
    {
      id: "168",
      img: "./DataBase/productImages/Accessories/men12.jfif",
      brand: "GenZzz",
      title: "2-pack necklaces",
      price: "519",
      category: "men",
    },
    {
      id: "169",
      img: "./DataBase/productImages/Accessories/women1.jfif",
      brand: "GenZzz",
      title: "Linked-ring necklace",
      price: "299",
      category: "women",
    },
    {
      id: "170",
      img: "./DataBase/productImages/Accessories/women2.jfif",
      brand: "GenZzz",
      title: "Crossbody bag",
      price: "1499",
      category: "women",
    },
    {
      id: "171",
      img: "./DataBase/productImages/Accessories/women3.jfif",
      brand: "GenZzz",
      title: "Pendant necklace",
      price: "299",
      category: "women",
    },
    {
      id: "172",
      img: "./DataBase/productImages/Accessories/women4.webp",
      brand: "GenZzz",
      title: "Sphere-detail front and back earrings",
      price: "699",
      category: "women",
    },
    {
      id: "173",
      img: "./DataBase/productImages/Accessories/women5.jfif",
      brand: "GenZzz",
      title: "Belt",
      price: "649",
      category: "women",
    },
    {
      id: "174",
      img: "./DataBase/productImages/Accessories/women6.jfif",
      brand: "GenZzz",
      title: "Bow-decorated scrunchie",
      price: "399",
      category: "women",
    },
    {
      id: "175",
      img: "./DataBase/productImages/Accessories/women7.jfif",
      brand: "GenZzz",
      title: "Bead-detail lariat necklace",
      price: "599",
      category: "women",
    },
    {
      id: "176",
      img: "./DataBase/productImages/Accessories/women8.jfif",
      brand: "GenZzz",
      title: "Shopper",
      price: "999",
      category: "women",
    },
    {
      id: "177",
      img: "./DataBase/productImages/Accessories/women9.jfif",
      brand: "GenZzz",
      title: "Large shopper",
      price: "449",
      category: "women",
    },
    {
      id: "178",
      img: "./DataBase/productImages/Accessories/women10.jfif",
      brand: "GenZzz",
      title: "Jacquard-weave handbag",
      price: "689",
      category: "women",
    },
    {
      id: "179",
      img: "./DataBase/productImages/Accessories/women11.jfif",
      brand: "GenZzz",
      title: "Mobile phone decoration",
      price: "239",
      category: "women",
    },
    {
      id: "180",
      img: "./DataBase/productImages/Accessories/women12.jfif",
      brand: "GenZzz",
      title: "Pendant necklace",
      price: "299",
      category: "women",
    },
    {
      id: "181",
      img: "./DataBase/productImages/Accessories/kid1.jfif",
      brand: "GenZzz",
      title: "Quilted crossbody bag",
      price: "1499",
      category: "kid",
    },
    {
      id: "182",
      img: "./DataBase/productImages/Accessories/kid2.jfif",
      brand: "GenZzz",
      title: "2-pack hair claws",
      price: "299",
      category: "kid",
    },
    {
      id: "183",
      img: "./DataBase/productImages/Accessories/kid3.jfif",
      brand: "GenZzz",
      title: "2-pack sunglasses",
      price: "799",
      category: "kid",
    },
    {
      id: "184",
      img: "./DataBase/productImages/Accessories/kid4.jfif",
      brand: "GenZzz",
      title: "Hair elastics and clips",
      price: "299",
      category: "kid",
    },
    {
      id: "185",
      img: "./DataBase/productImages/Accessories/kid5.jfif",
      brand: "GenZzz",
      title: "2-pack bow-detail hairbands",
      price: "699",
      category: "kid",
    },
    {
      id: "186",
      img: "./DataBase/productImages/Accessories/kid6.jfif",
      brand: "GenZzz",
      title: "Cotton bucket hat",
      price: "399",
      category: "kid",
    },
    {
      id: "187",
      img: "./DataBase/productImages/Accessories/kid7.jfif",
      brand: "GenZzz",
      title: "3-pack braided hair elastics",
      price: "149",
      category: "kid",
    },
    {
      id: "188",
      img: "./DataBase/productImages/Accessories/kid8.jfif",
      brand: "GenZzz",
      title: "Cotton canvas gym bag",
      price: "489",
      category: "kid",
    },
    {
      id: "189",
      img: "./DataBase/productImages/Accessories/kid9.jfif",
      brand: "GenZzz",
      title: "2-pack beaded bracelets",
      price: "399",
      category: "kid",
    },
    {
      id: "190",
      img: "./DataBase/productImages/Accessories/kid10.jfif",
      brand: "GenZzz",
      title: "Sunglasses",
      price: "699",
      category: "kid",
    },
    {
      id: "191",
      img: "./DataBase/productImages/Accessories/kid11.jfif",
      brand: "GenZzz",
      title: "4-pack hair clips",
      price: "279",
      category: "kid",
    },
    {
      id: "192",
      img: "./DataBase/productImages/Accessories/kid12.jfif",
      brand: "GenZzz",
      title: "Belt",
      price: "799",
      category: "kid",
    },
  ],

};
